### ISSUE TITLE
Was this ever solved?

### ISSUE THREAD

**Issue by arberx** [mgetka/haproxy-grpc-issue#1]
Running into a similar issue, wondering if you made any progress?

**Comment by mgetka** [comment]
Here is a [link to my post on HAProxy board](https://discourse.haproxy.org/t/unable-to-receive-grpc-error-during-a-response-streaming-call-using-haproxy-in-http-mode/6102) that I wrote when I have encountered the issue - it contains my insight on the problem, but no response.

ATM I'm working with a custom HAProxy build with a nasty workaround so I haven't been tracking whether anything has changed.

**Comment by santigl** [comment]
Thanks for that detailed write up and the scripts to easily recreate it!

I just ran the docker-compose setup updating grpcio to v1.37.0 and HAProxy to v2.4, and the results are identical.

Do you think it could be worth filing that as a bug on https://github.com/haproxy/haproxy/issues, @mgetka?

**Comment by mgetka** [comment]
Seeing that the issue doesn't affect just me I'm more confident that it is not just my silly mistake :sweat_smile: I'll fill an issue to HAProxy repo.

**Comment by mgetka** [comment]
https://github.com/haproxy/haproxy/issues/1219

**Comment by arberx** [comment]
Great, I'll close this issue in favor of discussion in the official repo. 

Thank you!
